/*

Given a string (sequence of characters) of length n, generate all of its subsequences. 

A subsequence of a given string (sequence) is a string (sequence) that is generated by 
removing zero or more characters from the given string (sequence) without changing its 
order.

Example
	
	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints
 
  1 < n < 10

*/

#include<iostream>
// Program to generate the subsequences of a given string.
using namespace std;

void generateSubsequences(char* inp, int i, char* out, int j) {
	// base case
	if(inp[i] == '\0') {
		out[j] = '\0';
		cout << out << endl;
		return;
	}

	// recursive case

	// I am standing at the ith character and I have to take a decision

	// 1. include the ith character in the out subseq.
	out[j] = inp[i];
	generateSubsequences(inp, i+1, out, j+1);
	
	// 2. exclude the ith character from the out subseq.
	generateSubsequences(inp, i+1, out, j);

}

int main() {

	char inp[] = "abc";
	char out[10];

	generateSubsequences(inp, 0, out, 0);
	
	return 0;
}
